version: '3.8'

services:
  mongo1:
    image: mongo:4.4
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - mongo_cluster
    volumes:
      - mongo1_data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo2:
    image: mongo:4.4
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - mongo_cluster
    volumes:
      - mongo2_data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo3:
    image: mongo:4.4
    container_name: mongo3
    ports:
      - "27019:27017"
    networks:
      - mongo_cluster
    volumes:
      - mongo3_data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mongo_cluster:
    driver: bridge

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
